"use client";

import React, { useState } from "react";
import {
  Newspaper,
  Sun,
  Clock,
  Moon,
  CalendarDays,
  CalendarRange,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  RotateCcw,
  TrendingUp,
  AlertTriangle,
  BrainCircuit,
  BarChart3,
} from "lucide-react";

type BriefingType =
  | "MORNING_BRIEF"
  | "MIDDAY_UPDATE"
  | "CLOSING_REPORT"
  | "WEEKLY_REVIEW"
  | "MONTHLY_REVIEW";

interface EvidenceLink {
  title: string;
  source: string;
  url: string;
}

interface BriefingDocument {
  briefing_id: string;
  briefing_type: BriefingType;
  generated_at_utc: string;
  period_label: string;
  executive_summary: string;
  key_market_events: string[];
  ai_decisions_made: Array<{ reasoning_id?: string; action: string; confidence: number }>;
  portfolio_changes: Array<{ fund_id: string; name: string; cagr_pct: number; sharpe_ratio: number }>;
  confidence_changes: Array<{ reasoning_id?: string; confidence: number; at?: string; note?: string }>;
  risk_changes: Array<{ metric: string; value: string; change: string }>;
  forecast_changes: Array<{ scenario: string; probability: number; change: string }>;
  evidence_links: EvidenceLink[];
  replay_links: string[];
  timeline_event_count: number;
  disclaimer: string;
}

const BRIEFING_TYPES: { type: BriefingType; label: string; Icon: React.ElementType; color: string }[] = [
  { type: "MORNING_BRIEF", label: "Morning Brief", Icon: Sun, color: "amber" },
  { type: "MIDDAY_UPDATE", label: "Midday Update", Icon: Clock, color: "blue" },
  { type: "CLOSING_REPORT", label: "Closing Report", Icon: Moon, color: "violet" },
  { type: "WEEKLY_REVIEW", label: "Weekly Review", Icon: CalendarDays, color: "teal" },
  { type: "MONTHLY_REVIEW", label: "Monthly Review", Icon: CalendarRange, color: "rose" },
];

const MOCK_BRIEFING: BriefingDocument = {
  briefing_id: "brief_a1b2c3d4e5",
  briefing_type: "MORNING_BRIEF",
  generated_at_utc: "2026-08-04T05:00:00Z",
  period_label: "2026-08-04 Morning Brief",
  executive_summary:
    "Good morning. AlphaMind v2 monitored 47 market events overnight. Key themes include continued semiconductor sector strength, elevated macro uncertainty from FOMC minutes, and stable fixed income spreads. The Growth AI Fund leads the leaderboard by composite score.",
  key_market_events: [
    "FORECAST_UPDATED: Reasoning Stored — Increase NVDA allocation to 40%",
    "PORTFOLIO_REBALANCED: Growth Fund rebalanced — Sharpe 1.45",
    "BRIEFING_GENERATED: 2026-08-03 Closing Report generated",
    "FORECAST_UPDATED: Conservative Fund fixed income hedge trigger",
    "PORTFOLIO_REBALANCED: Balanced Fund routine quarterly rebalance",
  ],
  ai_decisions_made: [
    { reasoning_id: "rsn_a4b2c18d91", action: "Increase NVDA allocation to 40%", confidence: 0.88 },
    { reasoning_id: "rsn_b7d4e92f12", action: "Increase TLT fixed income weighting to 50%", confidence: 0.92 },
  ],
  portfolio_changes: [
    { fund_id: "GROWTH", name: "Growth Fund", cagr_pct: 18.5, sharpe_ratio: 1.45 },
    { fund_id: "BALANCED", name: "Balanced Fund", cagr_pct: 11.2, sharpe_ratio: 1.62 },
    { fund_id: "CONSERVATIVE", name: "Conservative Fund", cagr_pct: 6.5, sharpe_ratio: 1.85 },
  ],
  confidence_changes: [
    { reasoning_id: "rsn_a4b2c18d91", confidence: 0.88, at: "2026-08-04T04:30:00Z" },
    { reasoning_id: "rsn_b7d4e92f12", confidence: 0.92, at: "2026-08-04T02:15:00Z" },
  ],
  risk_changes: [
    { metric: "VaR (95%)", value: "2.1%", change: "-0.3%" },
    { metric: "CVaR (95%)", value: "3.4%", change: "-0.5%" },
  ],
  forecast_changes: [
    { scenario: "Bull", probability: 0.42, change: "+0.05" },
    { scenario: "Base", probability: 0.38, change: "-0.02" },
    { scenario: "Bear", probability: 0.20, change: "-0.03" },
  ],
  evidence_links: [
    { title: "SEC EDGAR NVDA 10-K Item 7", source: "SEC EDGAR", url: "https://www.sec.gov/" },
    { title: "FRED PCE Inflation Series", source: "Federal Reserve", url: "https://fred.stlouisfed.org/" },
  ],
  replay_links: ["evt_c918a2b4f1", "evt_d3a1b9c0e2", "evt_f4c2d0a1b8"],
  timeline_event_count: 47,
  disclaimer:
    "This briefing is generated by an autonomous AI system for informational and educational purposes only. It does not constitute investment advice. — AlphaMind AI, SEC/FINRA Research Disclaimer",
};

const colorMap: Record<string, string> = {
  amber: "text-amber-400 bg-amber-500/10 border-amber-500/20",
  blue: "text-blue-400 bg-blue-500/10 border-blue-500/20",
  violet: "text-violet-400 bg-violet-500/10 border-violet-500/20",
  teal: "text-teal-400 bg-teal-500/10 border-teal-500/20",
  rose: "text-rose-400 bg-rose-500/10 border-rose-500/20",
};

const SectionToggle = ({ title, icon: Icon, children, color = "slate" }: { title: string; icon: React.ElementType; children: React.ReactNode; color?: string }) => {
  const [open, setOpen] = useState(true);
  return (
    <div className="border border-slate-800 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen((o) => !o)}
        className="w-full flex items-center justify-between px-4 py-3 bg-slate-900 hover:bg-slate-800/80 transition"
      >
        <div className="flex items-center gap-2">
          <Icon className={`w-4 h-4 text-${color}-400`} />
          <span className="text-sm font-semibold text-slate-200">{title}</span>
        </div>
        {open ? <ChevronUp className="w-4 h-4 text-slate-500" /> : <ChevronDown className="w-4 h-4 text-slate-500" />}
      </button>
      {open && <div className="bg-slate-950/60 p-4">{children}</div>}
    </div>
  );
};

export default function BriefingsPage() {
  const [selectedType, setSelectedType] = useState<BriefingType>("MORNING_BRIEF");
  const briefing = MOCK_BRIEFING;

  const typeConfig = BRIEFING_TYPES.find((t) => t.type === selectedType)!;

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-8">
      <div className="max-w-5xl mx-auto space-y-8">

        {/* Header */}
        <div className="border-b border-slate-800 pb-6">
          <div className="flex items-center gap-2 mb-2">
            <span className="px-2.5 py-1 rounded-full text-xs font-semibold bg-violet-500/10 text-violet-400 border border-violet-500/20">AlphaMind v2.0 — Milestone 20</span>
          </div>
          <h1 className="text-3xl font-bold tracking-tight text-white flex items-center gap-3">
            <Newspaper className="w-8 h-8 text-violet-400" />
            Daily Automated Briefings
          </h1>
          <p className="text-slate-400 text-sm mt-1">
            AI-generated briefings sourced from Unified Timeline, Reasoning Memory, and Portfolio Engine.
          </p>
        </div>

        {/* Briefing Type Selector */}
        <div className="flex flex-wrap gap-3">
          {BRIEFING_TYPES.map(({ type, label, Icon, color }) => (
            <button
              key={type}
              onClick={() => setSelectedType(type)}
              className={`flex items-center gap-2 px-4 py-2 rounded-xl border text-sm font-semibold transition-all ${
                selectedType === type
                  ? colorMap[color] + " ring-1 ring-current"
                  : "bg-slate-900 border-slate-800 text-slate-400 hover:border-slate-700"
              }`}
            >
              <Icon className="w-4 h-4" /> {label}
            </button>
          ))}
        </div>

        {/* Briefing Document */}
        <div className="space-y-4">
          {/* Header Card */}
          <div className={`rounded-xl border p-5 ${colorMap[typeConfig.color]}`}>
            <div className="flex items-start justify-between">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <typeConfig.Icon className="w-5 h-5" />
                  <span className="text-sm font-semibold uppercase tracking-wider">{typeConfig.label}</span>
                </div>
                <h2 className="text-lg font-bold text-white">{briefing.period_label}</h2>
                <p className="text-xs opacity-70 mt-1">{briefing.generated_at_utc} · {briefing.timeline_event_count} timeline events</p>
              </div>
              <span className="text-xs font-mono opacity-60">{briefing.briefing_id}</span>
            </div>
          </div>

          {/* Executive Summary */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
            <p className="text-base text-slate-200 leading-relaxed">{briefing.executive_summary}</p>
          </div>

          {/* Key Market Events */}
          <SectionToggle title="Key Market Events" icon={TrendingUp} color="emerald">
            <ul className="space-y-2">
              {briefing.key_market_events.map((evt, i) => (
                <li key={i} className="text-sm text-slate-300 flex items-start gap-2">
                  <span className="mt-1 w-1.5 h-1.5 rounded-full bg-emerald-500 flex-shrink-0" />
                  {evt}
                </li>
              ))}
            </ul>
          </SectionToggle>

          {/* AI Decisions */}
          <SectionToggle title="AI Decisions Made" icon={BrainCircuit} color="violet">
            <div className="space-y-3">
              {briefing.ai_decisions_made.map((d, i) => (
                <div key={i} className="flex items-start justify-between gap-4 bg-slate-900 border border-slate-800 rounded-lg p-3">
                  <p className="text-sm text-slate-200 flex-1">{d.action}</p>
                  <span className={`text-xs font-bold px-2 py-0.5 rounded flex-shrink-0 ${d.confidence >= 0.85 ? "bg-emerald-500/10 text-emerald-400" : "bg-amber-500/10 text-amber-400"}`}>
                    {(d.confidence * 100).toFixed(0)}%
                  </span>
                </div>
              ))}
            </div>
          </SectionToggle>

          {/* Portfolio Changes */}
          <SectionToggle title="Portfolio Changes" icon={BarChart3} color="blue">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-xs text-slate-400 border-b border-slate-800">
                    <th className="text-left pb-2">Fund</th>
                    <th className="text-right pb-2">CAGR</th>
                    <th className="text-right pb-2">Sharpe</th>
                  </tr>
                </thead>
                <tbody>
                  {briefing.portfolio_changes.map((p, i) => (
                    <tr key={i} className="border-b border-slate-800/50">
                      <td className="py-2 text-slate-200">{p.name}</td>
                      <td className="py-2 text-right text-emerald-400 font-mono">{p.cagr_pct.toFixed(1)}%</td>
                      <td className="py-2 text-right text-blue-400 font-mono">{p.sharpe_ratio.toFixed(2)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </SectionToggle>

          {/* Risk & Forecast Changes */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <SectionToggle title="Risk Changes" icon={AlertTriangle} color="rose">
              {briefing.risk_changes.map((r, i) => (
                <div key={i} className="flex justify-between text-sm py-1 border-b border-slate-800/50 last:border-0">
                  <span className="text-slate-400">{r.metric}</span>
                  <div className="text-right">
                    <span className="text-slate-200 font-mono mr-2">{r.value}</span>
                    <span className="text-emerald-400 text-xs font-mono">{r.change}</span>
                  </div>
                </div>
              ))}
            </SectionToggle>

            <SectionToggle title="Forecast Changes" icon={TrendingUp} color="teal">
              {briefing.forecast_changes.map((f, i) => (
                <div key={i} className="flex justify-between text-sm py-1 border-b border-slate-800/50 last:border-0">
                  <span className={`font-semibold ${f.scenario === "Bull" ? "text-emerald-400" : f.scenario === "Bear" ? "text-rose-400" : "text-slate-400"}`}>{f.scenario}</span>
                  <div className="text-right">
                    <span className="text-slate-200 font-mono mr-2">{(f.probability * 100).toFixed(0)}%</span>
                    <span className="text-teal-400 text-xs font-mono">{f.change}</span>
                  </div>
                </div>
              ))}
            </SectionToggle>
          </div>

          {/* Evidence Links & Replay Links */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
              <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">Evidence Links</h3>
              {briefing.evidence_links.map((e, i) => (
                <a key={i} href={e.url} target="_blank" rel="noopener noreferrer"
                  className="flex items-center justify-between gap-2 text-sm text-emerald-300 hover:text-emerald-200 py-1.5 border-b border-slate-800/50 last:border-0">
                  {e.title} <ExternalLink className="w-3.5 h-3.5 flex-shrink-0" />
                </a>
              ))}
            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
              <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">Replay Links</h3>
              {briefing.replay_links.map((r, i) => (
                <div key={i} className="flex items-center gap-2 py-1.5 border-b border-slate-800/50 last:border-0">
                  <RotateCcw className="w-3.5 h-3.5 text-teal-400" />
                  <span className="text-xs font-mono text-teal-300">{r}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Disclaimer */}
          <div className="bg-slate-900/40 border border-slate-800 rounded-xl p-4">
            <p className="text-xs text-slate-500 leading-relaxed">{briefing.disclaimer}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
