apiVersion: v1
kind: Service
metadata:
  name: alphamind-backend-service
spec:
  type: ClusterIP
  selector:
    app: alphamind-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
